### ISSUE TITLE
NOT Working on Safari

### ISSUE THREAD

**Issue by GJ2511** [schiehll/react-alert#10]
@schiehll   Alert component not working on safari.

Even Tried Demo link :- http://schiehll.github.io/react-alert/

getting following error:- 

TypeError: 'undefined' is not a function (evaluating 'Object.assign(alert, options)')

Can you fix this urgently, Please

**Comment by GJ2511** [comment]
@schiehll   Any updates???

**Comment by dherran** [comment]
Project is no longer maintained and will likely not be fixed.

I suggest forking it and fixing the issue manually on your own if you really need the module.

**Comment by GJ2511** [comment]
ok Thx

**Comment by GJ2511** [comment]
@schiehll @dherran  Fixed Es6 support on safari . Do you want me to create a pull request so that you can publish new module
