### ISSUE TITLE
Alert Showing Twice When Transition Set To 'Scale'

### ISSUE THREAD

**Issue by saiemsaeed** [schiehll/react-alert#101]
I installed and setup package as per documentation on github. I set transition to 'scale' in alertOptions while setup and when tested, i was getting alert twice, initially i thought its issue with my implementation, i double checked all the code but got no clue, then i tried setting transition to 'fade' and woah i got alert only once. It means there is some issue with the 'scale' transition. Good to hear back from @schiehll soon.

P.S I have added ZIP file containing screen recording of issue, please have a look.

[Glitch in ReactAlert.mov.zip](https://github.com/schiehll/react-alert/files/2859034/Glitch.in.ReactAlert.mov.zip)

**Comment by schiehll** [comment]
Hey @saiemsaeed can you fork [this](https://codesandbox.io/s/l2mo430lzq) codesandbox and try to reproduce it? I tried to but couldn't. 

If you can reproduce it in a codesandbox where I can take a look in the code, then I can help you.

**Comment by saiemsaeed** [comment]
@schiehll Let me try it

**Comment by saiemsaeed** [comment]
@schiehll i am not able to repro it, with alert basic template you provided... Maybe some issue with the my custom template, I am closing this!

**Comment by schiehll** [comment]
@saiemsaeed FWIW I don't think the problem is in the transition, I think that it is only making easier to you to see the problem, but the fade transition ones are probably showing twice too.

**Comment by saiemsaeed** [comment]
@schiehll if you see in the video, when transition is on scale, alert pops up and then closes immediately and then again pops up, which is weird. Maybe it also happens with fade transition, and due to fade it's not so obvious, but i don't think so. I will update you, if i get to solution or problem's reason.
