### ISSUE TITLE
Attempted import error: 'useAlert' is not exported from 'react-alert'

### ISSUE THREAD

**Issue by Pradnyana28** [schiehll/react-alert#106]
I'm trying to import useAlert hook but get an unexpected output.

index.js
`import { Provider as AlertProvider } from 'react-alert'
import AlertTemplate from 'react-alert-template-basic'

<AlertProvider template={AlertTemplate} timeout={5000} position="bottom right">
            <ErrorBoundary render={() => <div className="errorWrapper">Ooops, error brohh!</div>}>
                <App />
            </ErrorBoundary>
</AlertProvider>`

somewhere.js
`import { useAlert } from 'react-alert'

const login = () => {
        const alert = useAlert()
        alert.show('err')
}`

Is there something wrong or any typo in my code ? thank you.

**Comment by schiehll** [comment]
Hey @Pradnyana28 what version of the lib are you using? `useAlert` was introduced in v5, so if you are using v5 you should be good.

If that's the case, can you reproduce it in a codesandbox? Without seeing the code it's hard to help.

**Comment by Pradnyana28** [comment]
I see, maybe i need to read the docs carefully 👍

**Comment by littlefroginnovations** [comment]
I am having this same issue with 5.5.0

**Comment by vincenttern** [comment]
Im having the same issue with version 6 and 5.5, i have react version 16.9

**Comment by littlefroginnovations** [comment]
as you can see from separate issues posted about this they are not interested in fixing. I even posted my own issue and documented it but because i didnt post with example code they marked it as false bug and closed the issue. there are better packages out there for alert. Check out react-redux-toastr its a way better package

**Comment by besLisbeth** [comment]
I just checked out that everything works with 
```
"react": "^16.12.0",
"react-alert": "^6.0.0"
```
Unfortunately, nothing can be done without the full example code or working sandbox.
