### ISSUE TITLE
How to use it inside a class component

### ISSUE THREAD

**Issue by B-sirius** [schiehll/react-alert#116]
Here is the [example](https://codesandbox.io/s/zkyn6z3vrl).
I wanna use it inside a **class component**, and get the error **"Hooks can only be called inside the body of a function component"**.
I'm not sure if there's a problem with my code or if it's only supporting usage in function component

**Comment by mikhailrojo** [comment]
Hi B-seirius use withHook
```
import { withAlert } from "react-alert";
...
export default withAlert()(Home)

```
and invoke it with
```
this.props.alert.show()
```

**Comment by B-sirius** [comment]
> Hi B-seirius use withHook
> 
> ```
> import { withAlert } from "react-alert";
> ...
> export default withAlert()(Home)
> ```
> 
> and invoke it with
> 
> ```
> this.props.alert.show()
> ```

that works! thanks for helping

**Comment by luizhenriquerosa** [comment]
Sorry, for me dont work this.props.alert.show()

**Comment by luizhenriquerosa** [comment]
`import React, {Component} from 'react';
import {Typography, withStyles, Paper, Container, FormControlLabel, Checkbox, Button} from '@material-ui/core/';
import {indigo} from '@material-ui/core/colors';
import axios from 'axios';
import Alerta from '../componentes/Alerta'
import compose from 'recompose/compose';
import {withAlert} from 'react-alert'

const alert = withAlert()

const styles = theme => ({
        // css
});

class SelecionarFiliais extends Component{
    constructor(props) {
        super(props);
        document.title = 'Adapta Web - Selecione as filiais';
        this.eventoChange = this.eventoChange.bind(this);
        this.eventoClick = this.eventoClick.bind(this);
        this.gerarFormCheckbox = this.gerarFormCheckbox.bind(this);
        this.gerarCheckbox = this.gerarCheckbox.bind(this);
        this.gerarAlerta = this.gerarAlerta.bind(this);
        this.state = {
            formCheckbox: '',
            id_filial: [],
        }
    }

    componentWillMount() {
        let self = this;
        const params = {
            id_login: this.props.location.state.id_login
        }
        const headers = {
            Authorization: 'Bearer ' + localStorage.getItem('JWT_TOKEN')
        }
        axios.post('http://localhost/adapta_api/public/api/buscaFiliais', params, {headers: headers})
        .then(function(response) {
            const resultado = response.data.data
            if (resultado.lenght === 1){
                self.props.history.push('/', { id_filial: resultado.user_id})
            } else {
                const checkbox = self.gerarFormCheckbox(resultado);
                self.setState({
                    formCheckbox: checkbox
                })
            }
        })
        .catch(function(error){
            if (error.response){
                alert(error.response.data.message);
            } else if (error.request){
                alert(error.message);
            } else{
                alert(error.message);
            }
        });
    }

    gerarAlerta(titulo, texto, nomeBotao){
        return <Alerta open='true' titulo={titulo} texto={texto} nomeBotao={nomeBotao}></Alerta>;
    }

    gerarCheckbox(array) {
        const checkbox = array.map((e) => {
            return <FormControlLabel
                control = {
                    <Checkbox
                        onChange = {this.eventoChange}
                        value = {e.id}
                        color = "primary"
                    />
                }
                label = {e.razaoSocial + " " + e.cnpj}
                key = {e.id}
            />
        })
        return checkbox
    }

    gerarFormCheckbox(array) {
        return (
            <Container maxWidth="xs">
                <Paper className={this.props.classes.paper}>
                    <form className={this.props.classes.form} noValidate>
                        <Typography component="h1" variant="h5"> Selecione as filiais </Typography>
                        {this.gerarCheckbox(array)}
                        <Button
                            fullWidth
                            variant="contained"
                            color="primary"
                            className={this.props.classes.botao}
                            onClick={this.eventoClick}
                        >
                        Avançar
                        </Button>
                    </form>
                </Paper>    
            </Container>
        );
    }

    eventoChange(event) {
        const target = event.target
        const value = target.value
        const name = target.name
        const checked = target.checked
        if (checked) {
            this.setState({
                [name]: value,
                id_filial: [...this.state.id_filial, value]
            });
        } else {
            let temp = this.state.id_filial
            temp = temp.filter((e) => e !== value)
            this.setState({
                [name]: value,
                id_filial: [temp]
            });
        }
    }

    eventoClick() {
        if (this.state.id_filial.length === 0) {
            this.props.alert.show(<div style={{ color: 'blue' }}>Some Message</div>);
            // const alert = alert.show(this.gerarAlerta('Aviso','Selecione pelo menos uma filial para continuar.','OK'));
        } else {
            sessionStorage.setItem('ID_FILIAL', this.state.id_filial);
            this.props.history.push('/')
        }
    }

    render () {
        return this.state.formCheckbox
    }
}

export default compose(
    withStyles(styles),
    withAlert(),
)(SelecionarFiliais);
`

**Comment by besLisbeth** [comment]
Hi, @luizhenriquerosa.

Can you please provide the sandbox with an example?
