### ISSUE TITLE
position option not working

### ISSUE THREAD

**Issue by jamesscaggs** [schiehll/react-alert#12]
I am unable to get the position option to render correctly. Here is my showAlert function:

`showAlert() {
    this.msg.success('SNAPSHOT ADDED SUCCESSFULLY!', {
    time: 50000,
    type: 'success',
    transition: 'scale',
    theme: 'light',
    position: 'top right',
    });
  }`

**Comment by schiehll** [comment]
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.
