### ISSUE TITLE
Custom Alert Types

### ISSUE THREAD

**Issue by kauffmanes** [schiehll/react-alert#121]
Is there a way to add types of alerts? For example, I use error, info, and success, but I'd also like a "warn" that is yellow. Is there a preferred way of doing that, or am I limited to the existing types and adding styling? I read the other issues and didn't see anything that answered my questions, so sorry if this is a duplicate and I just am misunderstanding.

**Comment by schiehll** [comment]
Hey @kauffmanes!

So actually there's no way to add a new type, BUT you can pass any custom option while calling an alert, and it would be passed to the template.

So if you have a [custom template](https://github.com/schiehll/react-alert#using-a-custom-alert-template), you can do something like:

```js
const AlertTemplate = ({ style, options, message, close }) => (
  <div style={style}>
    {options.CUSTOM_TYPE === 'warn' && 'you are being warned: '}
    {options.type === 'info' && '!'}
    {options.type === 'success' && ':)'}
    {options.type === 'error' && ':('}
    {message}
    <button onClick={close}>X</button>
  </div>
)
```

And when calling an alert:

```js
alert.show('some warning', { CUSTOM_TYPE: 'warn' })
```

In this case, it would show an alert that says `you are being warned: some warning`.

Hope it helps!

**Comment by yerlantemir** [comment]
Hi, how could I achieve it with typescript ? I am facing error `TS2345: Argument of type '{ CUSTOM_TYPE: string; }' is not assignable to parameter of type 'AlertCustomOptionsWithType'.`
