### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by amillward** [schiehll/react-alert#124]
Hi,

I use react-alert throughout my site, and Sentry is telling me I'm getting many of this error each day;
![object values](https://user-images.githubusercontent.com/1857493/63169309-5c3c6000-c02e-11e9-9a4d-c10ac2dd903a.png)

I have not been able to reproduce the error, and I can't see from looking at the code why this would be happening. Anyone else having this issue or can spot what may be going on?

react-alert@5.5.0 
react@16.8.6

Thanks

**Comment by schiehll** [comment]
Hi @amillward!

So you are probably getting this error when someone accesses your site via IE:
![Screen Shot 2019-08-16 at 10 07 11](https://user-images.githubusercontent.com/5200983/63169812-1b345380-c00e-11e9-92ee-d70d105660ba.png)

I think this was introduced when @besLisbeth added the constants for positions, types, transitions, etc...I could be wrong tho.

You can add a polyfill for it in your site, or maybe we could change it to something like:
```js
Object.keys(positions).map(position => positions[position])
```

PRs are welcome.

**Comment by amillward** [comment]
![react-alert](https://user-images.githubusercontent.com/1857493/63171742-2601df00-c034-11e9-9817-ac26c9279274.gif)

Sentry is actually reporting a majority Safari/iPad users... :(

**Comment by schiehll** [comment]
Yeah, probably old devices running old versions of browsers...but the solutions stands: You can fix it by adding a polyfill for `Object.values` to your site, and we can also change the code for something else.

**Comment by schiehll** [comment]
It's fixed now in v6, thanks for reporting!

**Comment by tianchouczl** [comment]
> It's fixed now in v6, thanks for reporting!

in v6:
https://github.com/schiehll/react-alert/blob/5229d32e4060d4185e3174c63858b2d00e4730b7/src/Provider.js#L125
There's a  object.values() here that's forgotten
