### ISSUE TITLE
getting browserify error

### ISSUE THREAD

**Issue by HenrikBechmann** [schiehll/react-alert#13]
I'd love to use react-alert, but getting the following error:

Browserify Error { Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/stylus-loader/index.js!./alert.styl' from '/var/www/dev.budgetpedia.ca/node_modules/react-alert/dist'

I have react, react-dom and react-addons-css-transition-group as specified.

Any ideas?

**Comment by HenrikBechmann** [comment]
Yeah, too bad about the webpack dependency. Yes there are people out there who don't use webpack (yet).

I had to abandon.

**Comment by schiehll** [comment]
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.
