### ISSUE TITLE
next.js getInitialProps is consumed by withAlert

### ISSUE THREAD

**Issue by simb4** [schiehll/react-alert#139]
next.js static method `getInitialProps` is consumed by HOC. I assume it erases it on some step. Not sure why.
```
class Index extends React.Component {
  static async getInitialProps({ store, query }) {
    return { x: 5 };
  }

  render() {
    console.log(this.props.x); // undefined

  }
}
export default withAlert()(Index);
```

I think, it is not expected behavior.

**Comment by besLisbeth** [comment]
Hi @simb4.
`getInitialProps`  should not be consumed by `withAlert` HOC as it redirects the props to the wrapped Component  Do you have a sandbox with not working example?
