### ISSUE TITLE
Error icon

### ISSUE THREAD

**Issue by viko42** [schiehll/react-alert#14]
Hey, i've got a little problem with the icon. 
![icon](https://cloud.githubusercontent.com/assets/18552774/22997335/3c75b792-f3d2-11e6-9f55-9210037246ab.png)

My Code: 

`import React from 'react';`
`import AlertContainer from 'react-alert';`

`export default class App extends React.Component {`
`  constructor(props){`
  `  super(props);`
    `this.alertOptions = {`
      `offset: 10,`
      `position: 'top',`
      `theme: 'dark'`,
      `time: 5000,`
`      transition: 'scale'`
  `  };`
`  }`
`  showAlert(){`
`    this.msg.info('Connected', {`
  `    time: 5000,`
    `  type: 'info',`
     ` icon: <img src="img/error.png" alt="" />`
    `});`
  `}`
  `render(){`
   ` return(`
    `  <div>`
     `   <AlertContainer ref={a => this.msg = a} {...this.alertOptions} />`
      `  <button onClick={this.showAlert.bind(this)}>Show Alert</button>`
      `</div>`
    `);`
  `}`
`}`

I cant find out the problem

**Comment by pelhage** [comment]
you should save yourself and forget this project- it is unmaintained

**Comment by schiehll** [comment]
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.
