### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by tianchouczl** [schiehll/react-alert#146]
in issues:
https://github.com/schiehll/react-alert/issues/124

in v6:
https://github.com/schiehll/react-alert/blob/5229d32e4060d4185e3174c63858b2d00e4730b7/src/Provider.js#L125
There's a  object.values() here that's forgotten

_Originally posted by @tianchouczl in https://github.com/schiehll/react-alert/issues/124#issuecomment-576147608_

**Comment by schiehll** [comment]
Thanks for pointing it out! Fixed in the latest release.
