### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

### ISSUE THREAD

**Issue by anpct** [schiehll/react-alert#153]
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

**Comment by schiehll** [comment]
Yeah, I think we have to update our `react-transition-group` dependency. I will do that later, or you can submit a PR if you feel like it.

**Comment by anpct** [comment]
It doesn't seem to solve the issue, but it think you should also give it a try.

**Comment by anpct** [comment]
I don't think that's solving the issue.

**Comment by anpct** [comment]
I think changes need to be done to the code to adapt to the new version of react-transition-group.

**Comment by anpct** [comment]
I submitted a PR please check it.

**Comment by Patricio18** [comment]
I have de same error

**Comment by manishoctal** [comment]
Still the same. Any hack?

**Comment by schiehll** [comment]
It's just a warning in the dev env because of the react-transition-group. I've just fixed it by updating the dependency. 

Try v7.0.2 and see if it's fixed for you. If it's not, I can reopen it.

**Comment by manishoctal** [comment]
Yes, it is fixed now. 
Thanks for the quick reply :) Happy coding.

**Comment by Patricio18** [comment]
where I do the changed ?  I reinstall the pakage but not be fix the problem. Can I help me ?

**Comment by manishoctal** [comment]
@Patricio18 You should check the version in package.json, are you sure about that? Or you can do by uninstall and install again.
