### ISSUE TITLE
Missing Alert warning type support

### ISSUE THREAD

**Issue by nikitastryuk** [schiehll/react-alert#163]
Usually,  there are 4 alert types:
![image](https://user-images.githubusercontent.com/32720808/95608649-1cbca880-0a66-11eb-9d50-e6db3b42e066.png)

Any plans to extend api to support `WARNING` type?

export const types = {
  INFO: 'info',
  SUCCESS: 'success',
  WARNING: 'warning', // This one is missing
  ERROR: 'error'
}

alert.warning('msg'); // Can not be done in current version

**Comment by besLisbeth** [comment]
Hi @nikitastryuk, 

I think that you can try to do it via calling `alert.show('Message', { type: ''warning })` and writing your own `AlertTemplate` for the warning type. I suppose, that there won't be any problems with this, as this property passes directly to the template in the current implementation, but you won't be able to pass it as the default alert type to the `Provider` component.

I'm not sure about the extending of the library in the near time, I hope, that @schiehll  will help us to clarify the issue
