### ISSUE TITLE
peerDependencies

### ISSUE THREAD

**Issue by mdodge-ecgrow** [schiehll/react-alert#165]
Can you update the peerDependencies for react and react-dom to allow for 17?

**Comment by amillward** [comment]
I have put in a PR for this; https://github.com/schiehll/react-alert/pull/169

**Comment by chrispalka** [comment]
Any update on this?

**Comment by Edsonzhu** [comment]
Updates?

**Comment by schiehll** [comment]
Fixed on v7.0.3

**Comment by mdodge-ecgrow** [comment]
Thank you!  Now can you please update the peer dependencies on 'react-alert-template-basic'?
