### ISSUE TITLE
change the black background

### ISSUE THREAD

**Issue by sarahshul** [schiehll/react-alert#168]
Hi,
Thanks for the alert, it is really usefull.

Is it possible to change the background of the alert?

I want to change it from black to a different color.

Thanks.

**Comment by besLisbeth** [comment]
Hi @sarahshul. I think that the most convenient and the right way will be to create your own custom AlertTemplate (it's not so hard). But, you can also add the property to the following AlertTemplate: 
```
import React from "react";
import { render } from "react-dom";
import { positions, Provider } from "react-alert";
import AlertTemplate from "react-alert-template-basic";
import Home from "./Home";

const options = {
  timeout: 5000,
  position: positions.BOTTOM_CENTER
};

const CustomAlertTemplate = (props) => {
  return <AlertTemplate {...props} style={{backgroundColor: 'blue'}}/> //<---- customColor sets here
}

const App = () => (
  <Provider template={CustomAlertTemplate} {...options}>
    <Home />
  </Provider>
);

render(<App />, document.getElementById("root"));
```
but I think that it's not the best way to do so.
