### ISSUE TITLE
Test cases getting failed on using useAlert()

### ISSUE THREAD

**Issue by rakeshkk16** [schiehll/react-alert#179]
TypeError: Cannot read property 'current' of undefined

    > 14 |     let alert = useAlert();

I am not using useRef in my component and test cases started failing only after adding this react alert.

**Comment by Loorik** [comment]
I have the exact same Error using Typescript, testing with Jest in a create-react-app bootstrap

**Comment by JGKle** [comment]
I have this issue too. did anyone solve it? usealert seems to be the only thing breaking my unit tests :/

**Comment by JGKle** [comment]
Actually, found the solution. It's here: https://github.com/schiehll/react-alert/issues/148

(wrap in AlertProvider)
