### ISSUE TITLE
Showing Below the Model 

### ISSUE THREAD

**Issue by DynMatrix** [schiehll/react-alert#180]
Hi,
 
When we open a model view and trying to trigger alert. Alert showing backside the opened model.

Show to resolve the issue.

**Comment by mimre73** [comment]
> Hi,
> 
> When we open a model view and trying to trigger alert. Alert showing backside the opened model.
> 
> Show to resolve the issue.

use z-index in container style

`const options = {
      position: positions.BOTTOM_CENTER,
      timeout: 2000,
      offset: '30px',
      containerStyle:{zIndex:9999999999999},
      transition: transitions.SCALE
    }`
