### ISSUE TITLE
Cannot find module 'react-addons-css-transition-group'

### ISSUE THREAD

**Issue by thellimist** [schiehll/react-alert#2]
When installed with `npm i react-alert --save` I get the error `Cannot find module 'react-addons-css-transition-group'`. My npm version is `npm: '3.5.2'`

When I call `npm install react-addons-css-transition-group --save` I get the error
```
Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/stylus-loader/index.js!./alert.styl''
```

**Comment by schiehll** [comment]
@thellimist sorry for taking so long, I will see if I can solve this.

**Comment by thellimist** [comment]
I believe it is caused by your build method. I put the repo in my project,
changed the css to scss and used gulp to build it and works perfectly.

**Comment by schiehll** [comment]
yeah...I think that was an error with my configuration of the externals config in the webpack.config file. I think it is ok now with the 1.0.14 version. Thanks for point it out, I'm glad you was able to make it work.

**Comment by AlwaysAwake** [comment]
Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/stylus-loader/index.js!./alert.styl' from 'c:\Users\Koo Dong Hyun\gitprojects\web-react\node_modules\react-alert\dist'

**Comment by rohandas** [comment]
This project had so much potential!

**Comment by sercanov** [comment]
I'm having the same

```
ERROR in ./~/react-alert/dist/alert.js
Module not found: Error: Cannot resolve module 'react-addons-css-transition-group' in /Users/sercan/marang/node_modules/react-alert/dist
 @ ./~/react-alert/dist/alert.js 3:45-89
```

**Comment by zialink** [comment]
I get almost the same error

`ERROR in ./leadmanager/frontend/src/components/layout/alerts.js
Module not found: Error: Can't resolve 'react-alert;' in 'C:\Users\Isaiah Obi\Documents\python\react_lead_manager\leadmanager\frontend\src\components\layout'
 @ ./leadmanager/frontend/src/components/layout/alerts.js 20:0-41 48:15-24
 @ ./leadmanager/frontend/src/components/App.js
 @ ./leadmanager/frontend/src/index.js`

**Comment by besLisbeth** [comment]
Hi, @zialink. It looks to me like you import 'react-alert' with ';' inside the quotes. Did you try to remove it?

**Comment by zialink** [comment]
Yes, I did and it is working now. I was sleepy yesterday so I didn't see it. Thank you.
