### ISSUE TITLE
Stateless function components cannot have refs

### ISSUE THREAD

**Issue by Tzaphkiel** [schiehll/react-alert#22]
It seems that the Alertcontainer is not a stateful component. 

This causes an issue when defining `ref=""` in recent React implementations and react complains:

```javascript
Uncaught Error: Stateless function components cannot have refs.
    at invariant (invariant.js:44)
    at ReactCompositeComponentWrapper.attachRef (ReactCompositeComponent.js:846)
    at Object.addComponentAsRefTo (ReactOwner.js:69)
    at attachRef (ReactRef.js:23)
    at Object.ReactRef.attachRefs (ReactRef.js:42)
    at ReactCompositeComponentWrapper.attachRefs (ReactReconciler.js:23)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
...
```

I'm not sure because I could not get it to work on the cloned repository but it seems that to be a stateful `React.Component`  you need to initialize the state using either the constructor or the `getInitialState()` method...

So instead of:

```javascript
  state = {
    alerts: []
  }
```
 
do:

```javascript
constructor (props) {
  super(props)
  this.state = {alerts: []}
}
```

or 

```javascript
getInitialState() {
  return {alerts: []}
}
```

but for some reason in my tests when trying that, I still get the error.

Btw, on a side note you are doing this:

```javascript
this.setState(prevState => ({
  alerts: prevState.alerts.concat(alert)
}))
```

and thus _mutating_ the state instead of creating a new instance of it:

```javascript
this.setState(prevState => ({
  alerts: [...prevState.alerts, alert]
}))
```

using the ES6 spread operator. I think your remove method is actually OK as `Array.filter` actually creates a new Object.

**Comment by dennybiasiolli** [comment]
Hi @Tzaphkiel ,

I think that `getInitialState()` is an ES5 ways to set the default state. Setting state in the current way it's the same as doing it in the constructor.

Btw, `Array.concat` [does not change the existing array](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/concat?v=example), so `prevState.alerts` is not mutating ;)

**Comment by schiehll** [comment]
Hey @Tzaphkiel,

You should try to use the callback pattern when creating refs as recommended [here](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs) in the React docs.

Try that, and if it doesn't work maybe I can try to help you to figure out why.

Also, thank you @dennybiasiolli for the help! That was quick! 
You are right, concat does not mutate. And the component are in fact stateful, we are sure about it cause the lifecycle methods are working as expected.

**Comment by Tzaphkiel** [comment]
@dennybiasiolli yes you are right! In the quickness of my writing, I did not verify the documentation.
@schiehll yes I know about the proper working of the lifecycle methods and was therefore confused why it would call the component a stateless one...
This is how I use it (ES6):
```javascript
import AlertContainer from 'react-alert'
...
let alertcomp
...
const AppComp = ({history, store}) => (
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <div className='container-fluid'>
        <Header />

        <Switch>
          <Route exact path='/' component={Welcome} />
...
          <Route path='/about' component={About} />
          <Route component={NotFound} />
        </Switch>

        <Footer />
        <div id='pleaseWaitDialog'
          className='modal fade' tabIndex='-1'
          role='dialog' data-backdrop='static' data-keyboard='false'>
          <div className='modal-dialog'>
            <div className='modal-content'>
              <div className='modal-body'>
                <div className='progress'>
                  <div className='progress-bar progress-bar-striped active'
                    role='progressbar' aria-valuenow='100' aria-valuemin='0'
                    aria-valuemax='100' style={{width: '100%'}}>
                    <span className='sr-only'>100% Complete</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Dialog ref='dialog' />
        <AlertContainer ref={(a) => alertcomp = a} {...alertOptions} />
      </div>
    </ConnectedRouter>
  </Provider>
```

Initially I even had `ref={(a) => global.msg = a}`

Is that not the way to do it?

**Comment by Tzaphkiel** [comment]
:scream: writing the above and re-looking at the rendered comment again, I just noticed the mistake:

**Nothing to do with the react-alert.**

The `<Dialog ref='dialog' />` is the problem - obviously :rage:

Thank you again for the (very) quick response and help.

**Comment by dennybiasiolli** [comment]
The important thing is that the problem is solved! 😉 
Thank you for the feedback @Tzaphkiel !
