### ISSUE TITLE
how can I customize css style?

### ISSUE THREAD

**Issue by ok713** [schiehll/react-alert#26]

**Comment by dennybiasiolli** [comment]
Hi @ok713, you can refer to #20: 

> You can use a React Element as a message, so to add a text-transform you could do something like this:
> `this.msg.success(<div style={{textTransform: 'capitalize'}}>TEXT WILL BE CAPITALIZED</div>)`

Hope this helps!

**Comment by davidhu2000** [comment]
You can also use css only. 

Here is my code 

```jsx
<div className='alerts-container'>
  <AlertContainer ref={a => { this.msg = a; }} {...this.options} />
</div>
```

```scss
.alerts-container {
  > div[class^='css-'] > span > div[class^='css-'] {
    // entire alert styles here.

    div {

      // alert icon
      &:first-child {
      }
    
      // alert message div
      &:nth-child(2) {
      }

      // alert close div
      &:last-child {
      }
    }
  }
}
```

**Comment by dennybiasiolli** [comment]
@ok713 did you solved your issue?

**Comment by plysik** [comment]
It will be really handy if single alert container could have class depending on type to ease styling

**Comment by neilyoung** [comment]
@davidhu2000 What kind of CSS syntax is this? VSCode is not accepting it

**Comment by davidhu2000** [comment]
@neilyoung might be `scss`

**Comment by neilyoung** [comment]
@davidhu2000 Thanks for enlighten me :)

**Comment by schiehll** [comment]
with v3 you can now create custom alert templates, hope it helps!

**Comment by plysik** [comment]
Finally :) , but a little late. We had to migrate to another alerts package.
However this give us an oportunity to go back to use yours :)
