### ISSUE TITLE
Pressing on the close button resulting in error

### ISSUE THREAD

**Issue by xianghui** [schiehll/react-alert#27]
Pressing the close button resulting in [AlertContainer.js] **_onremoveAlert()** calling twice (one by the user's clicking action, and another because of the setTimeOut in AlertMessage.js

During the second time, 

**alertRemoved** would have been removed from this.state and thus undefined when it reaches this statement: 
alertRemoved.onClose && alertRemoved.onClose()

Probably should write it as:

alertRemoved && alertRemoved.onClose && alertRemoved.onClose()

**Comment by dennybiasiolli** [comment]
Thanks @xianghui for opening this issue, and thanks @davidhu2000 for the PR, this will be fixed later today 😉

**Comment by dennybiasiolli** [comment]
@xianghui issue fixed on master branch, @schiehll when you have some spare time can you please release a new patch version? Thanks!

**Comment by schiehll** [comment]
Thank you @dennybiasiolli and @davidhu2000 for your work! I've just published the new version.
