### ISSUE TITLE
position top center

### ISSUE THREAD

**Issue by erebolledo** [schiehll/react-alert#29]
Hi guys is there some way for get the position top center? I have been watching the code, but I have couldnt reach. Could you help me? Thanks

**Comment by jamesguan** [comment]
I agree, this would really be helpful for people who have a very center themed website.

**Comment by Aj1402** [comment]
I would like to work on this. It will be possible for a beginner like me!

**Comment by dennybiasiolli** [comment]
Thanks @Aj1402, if you will submit a PR we will happy to review it!

**Comment by Aj1402** [comment]
@dennybiasiolli I am new to reactJS and having trouble with testing the module fom my local directory i have tried using npm link, It shows the following error
![error](https://user-images.githubusercontent.com/16840665/29416385-83288f0c-8383-11e7-81d6-1cfd71c33a66.png)

**Comment by dennybiasiolli** [comment]
@Aj1402 did you already installed npm dependencies with `npm install` after cloning the repo?

**Comment by Aj1402** [comment]
@dennybiasiolli  Yes I did

**Comment by Aj1402** [comment]
@dennybiasiolli Alright i resolved the issue did the steps again from start this time it worked!

_Sent from my Lenovo A6020a46 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schiehll** [comment]
Fix in #42 by @Aj1402
