### ISSUE TITLE
Close button does not appear on Firefox 54.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by gitsad** [schiehll/react-alert#30]
On Firefox close button seems to not display svg button because of way of implementation: 
```background-image: url(data:image/svg+xml;utf8,<svg fill=\"#fff\" xmlns=\"http://www.w3.org/2000/s….83-2.83-11.17-11.17z\"/><path d=\"M0 0h48v48h-48z\" fill=\"none\"/></svg>);```. In my opinion, solution with ReactSVG with passing styles via className refers to developer chosen color could be better.

**Comment by apra** [comment]
The problem is the #, it must be escaped using %23.

**Comment by schiehll** [comment]
Published a new version with the fix proposed by @apra.

Thanks @apra for the fix!

**Comment by gitsad** [comment]
Thanks man
