### ISSUE TITLE
Auto Alert On Page Load

### ISSUE THREAD

**Issue by ahmadabugosh** [schiehll/react-alert#33]
Thanks for creating this great project, I found it really useful! 
I was wondering how you recommend if I want to go about loading it directly as soon as the page loads (instead of on button click). 

When I try loading it in componentWillMount I can't get it working. Any advice?

**Comment by ahmadabugosh** [comment]
I got it working with

componentDidMount(){
this.showAlert();
	}

thanks!

**Comment by dennybiasiolli** [comment]
Thanks for your feedback @ahmadabugosh 😄
