### ISSUE TITLE
Icon images not loading

### ISSUE THREAD

**Issue by buddythumbs** [schiehll/react-alert#34]
Hey, 

Great alert lib by the way!

The icons are not loading for me when I use the example in the readme.

Do I need to include anything aside from the example code?

Is it possible to have font icons in the icon? 

Thanks in advance!

**Comment by schiehll** [comment]
Hey @buddythumbs ,

You got any errors? Which browser are you using?

About the font icons question, sure, you can pass in a react element that renders a font icon.

**Comment by schiehll** [comment]
Should be fixed with v3.
