### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by ProductOfAmerica** [schiehll/react-alert#35]
Upon following the guide on the front page I get this error: `Unhandled Rejection (TypeError): Cannot read property 'show' of undefined`. I'm not sure how msg is defined or where to define it. Anything helps.

**Comment by schiehll** [comment]
Hey @ProductOfAmerica ,

You should define the `this.msg` (or whatever you wanna call it) in the ref prop of the `AlertContainer` component, like in the example in the docs:

```js
<AlertContainer ref={a => this.msg = a} {...this.alertOptions} />
```

Then you should be able to use it in any other function in that component that is being called after the initial render.

If you want to use it in child components, you should pass it down via props or any other way you like.

**Comment by ProductOfAmerica** [comment]
Sir,
When I do that, including the code directly from the home page I get this error:
![chrome_2017-07-25_18-22-50](https://user-images.githubusercontent.com/14712114/28597968-6b8e1bf2-7166-11e7-937c-6f01e83543c9.png)

If I change the code to look like this:
```jsx
import React, {Component} from 'react'
import AlertContainer from 'react-alert'

const alertOptions = {
  offset: 14,
  position: 'bottom left',
  theme: 'dark',
  time: 5000,
  transition: 'scale'
};

export default class App extends Component {

  showAlert = () => {
    this.msg.show('Some text or component', {
      time: 2000,
      type: 'success'
    })
  };

  render() {
    return (
      <div>
        <AlertContainer ref={a => this.msg = a} {...alertOptions} />
        <button onClick={this.showAlert}>Show Alert</button>
      </div>
    )
  }
}
```

It says this: 
![chrome_2017-07-25_18-24-55](https://user-images.githubusercontent.com/14712114/28597999-9711d390-7166-11e7-9147-8c552dbcfb91.png)


So then when I modify it to this:
```jsx
import React, {Component} from 'react'
import AlertContainer from 'react-alert'

const alertOptions = {
  offset: 14,
  position: 'bottom left',
  theme: 'dark',
  time: 5000,
  transition: 'scale'
};

export default class App extends Component {

  showAlert() {
    this.msg.show('Some text or component', {
      time: 2000,
      type: 'success'
    })
  };

  render() {
    return (
      <div>
        <AlertContainer ref={a => this.msg = a} {...alertOptions} />
        <button onClick={this.showAlert}>Show Alert</button>
      </div>
    )
  }
}
```

I get this:
![chrome_2017-07-25_18-26-44](https://user-images.githubusercontent.com/14712114/28598049-d44f29b0-7166-11e7-9829-0ac2da0b9486.png)

**Comment by dennybiasiolli** [comment]
@ProductOfAmerica Can you try with this code?
`onClick={this.showAlert.bind(this)}`

**Comment by schiehll** [comment]
Looks like @dennybiasiolli is right.

@ProductOfAmerica, you should either, bind like @dennybiasiolli said or in the constructor, or include the class properties transform [plugin](https://babeljs.io/docs/plugins/transform-class-properties/) in your babel config, so you could use the `showAlert = () =>` syntax.

**Comment by ProductOfAmerica** [comment]
@dennybiasiolli I get this:
![chrome_2017-07-26_19-55-49](https://user-images.githubusercontent.com/14712114/28649719-7611fe3c-723c-11e7-8aa9-e781f3099e25.png)

**Comment by lejager** [comment]
I'm having this same issue. I get this error message when calling the alert.
`VM302 2.563dabd1167c9ea261e5.js:3274 TypeError: Cannot read property 'success' of undefined`

I have multiple higher order components when calling the alert.
`export default withAlert(compose(
  graphql(createProject, { name: 'createProjectMutation' }),
  graphql(updateProject, { name: 'updateProjectMutation' }),
  graphql(CollectionAndSubjectsQuery),
)(ProjectFormWithData));`

I call the alert prop from a function. 
`// On form submit, send data to graphql.
  async createProject(input) {
    try {
      const data = await this.props.createProjectMutation({ 
        variables: { input },
        refetchQueries: [
          { query: ProjectListQuery },
          { query: CollectionAndSubjectsQuery }
        ]
      });
        const message = `Successfully created ${data.data.createProject.title}`;
        this.props.alert.success(message);

    } catch (err) {
      console.error(err);
      this.props.alert.error("We couldn't make your update at this time");
    };
  }
`
Here's my alert provider set up:
`import React, { Component } from 'react';
import { Provider as AlertProvider } from 'react-alert';
import AlertTemplate from 'react-alert-template-basic';
import Routes from './Routes.jsx';

const alertOptions = {
  position: 'top center',
  timeout: 4000,
  type: 'success',
  transition: 'fade',
  offset: '150px',
  zIndex: 999
}

export default class App extends Component {

  render() {
    return (
      <AlertProvider template={AlertTemplate} {...alertOptions}>
        <Routes />
      </AlertProvider>
    );
  }
}
`
