### ISSUE TITLE
Create generic Alert component

### ISSUE THREAD

**Issue by Itachi-Uchiha78** [schiehll/react-alert#36]
Hi, I'm in trouble on generalizing this component.

Let's say I got same App example in main page, renaming class as "MyAlert" and I put it inside a MyAlert.js file.
Then I would like to use it from other components...

If I import my custom alert component file like this:
`import MyAlert from './MyAlert';`
I've tried to do something like:

```
 functionCallAlert(){    
		 MyAlert.showAlert;
 }

```
But nothing happens. I don't want to put all the alert code in every component, is there a way to create a generic-importable component?

thanks

**Comment by BorisTB** [comment]
Try this

```
let alert

class Alert extends Component {
  alertOptions = {
    offset: 14,
    position: 'bottom left',
    theme: 'dark',
    time: 5000,
    transition: 'scale'
  }

  static showAlert () {
    alert.show('Some text or component', {
      time: 2000,
      type: 'success',
      icon: <i className='fa fa-exclamation' />
    })
  }

  render () {
    return (
      <div>
        <AlertContainer ref={a => { alert = a }} {...this.alertOptions} />
      </div>
    )
  }
}
```

then anywhere in code
```
import Alert from 'path/to/Alert'

Alert.showAlert()
```

**Comment by schiehll** [comment]
You can now create custom templates with v3.
