### ISSUE TITLE
Feature Request - Adding sound to alert

### ISSUE THREAD

**Issue by Aj1402** [schiehll/react-alert#37]
I have been using react-alert in one of my projects and have found it rally helpful. I thinking adding sound to the alert will be a really good improvement. I would like to work on this feature myself but I am very new to React and Open Source so I would appreciate some help.

**Comment by schiehll** [comment]
Hey @Aj1402, thank you for the suggestion but I don't think that's something to this lib do. You can easily do it in your project tho, doing something like this:

```js
showAlert = (msg, type) => {
  this.msg.show(msg, { type })
  someFunctionThatPlaysASound()
}
```

Hope it helps
