### ISSUE TITLE
auto close option and 'X' of alert not working in ie edge.

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [schiehll/react-alert#41]
![abc](https://user-images.githubusercontent.com/9972828/29569010-d42dc328-876f-11e7-9d60-8d0e3318c75d.jpg)

**Comment by dennybiasiolli** [comment]
Hi @Amara-Balakrishna1,
thanks for opening this issue.
I think that PR #38 is related to this issue, can you confirm this?

**Comment by Amara-Balakrishna1** [comment]
similar to that. and one more thing is  **use 0 to prevent auto close (apply to all alerts)**

{
  // defaults
  offset: 14, // the offset of the alert from the page border, can be any number
  position: 'bottom left', // the position of the alert, can be [bottom left, bottom right, top left, top right]
  theme: 'dark', // the color theme of the alert, can be [dark, light]
  time: 5000, // the time in milliseconds **to the alert close itself, use 0 to prevent auto close (apply to all alerts)**
  transition: 'scale' // the transition animation, can be [scale, fade]
}

**Comment by schiehll** [comment]
Should be working now with v3. Sorry about the delay and feel free to reopen it if v3 doesn't fix it for you.
