### ISSUE TITLE
Integration with Redux

### ISSUE THREAD

**Issue by glevha** [schiehll/react-alert#46]
Hi ! 
Thanks a lot for this great resource. This is exactly what I was looking for.
I am using Redux to manage my app's state. Do you have an idea of the best way to use this with React ? I want to avoid duplicating the `<AlertContainer />` component when I need my containers to trigger some alerts.

Thanks !

**Comment by falloutghost** [comment]
Just did exactly that.

***reducers/ui.js:***
```javascript
import { SHOW_ALERT_MESSAGE, HIDE_ALERT_MESSAGE } from '../constants';

const initialState = {
  alert: {
    show: false,
    msg: '',
    type: 'info',
  },
};

export default function ui(state = initialState, action) {
  // ...
  case SHOW_ALERT_MESSAGE:
    return {
      ...state,
      alert: {
        show: true,
        msg: action.payload.msg,
      },
    };
  case HIDE_ALERT_MESSAGE:
    return {
      ...state,
      alert: initialState.alert,
  };
  // ...
}
```

***actions/ui.js:***
```javascript
import { SHOW_ALERT_MESSAGE, HIDE_ALERT_MESSAGE } from '../constants';

export function showAlertMessage(msg, type = 'info') {
  return {
    type: SHOW_ALERT_MESSAGE,
    payload: {
      show: true,
      msg,
      type,
    }
  };
}

export function hideAlertMessage() {
  return {
    type: HIDE_ALERT_MESSAGE,
  };
}
```

Place the `<AlertContainer />` somewhere near your app's root or layout component, connect it to your store and add the following to your `componentWillReceiveProps` function:

```javascript
componentWillReceiveProps(nextProps) {
  if (nextProps.alert.show && nextProps.alert.msg) {
    this.msg.show(nextProps.alert.msg, {
      type: nextProps.alert.type,
      onClose: () => {
        this.props.hideAlertMessage();
      },
    });
  }
}

render() {
  // ...
  <AlertContainer
    ref={(msg) => { this.msg = msg; return true; }}
    {...alertOptions.default}
  />
}

// ...

const mapStateToProps = state => ({
  alert: state.ui.alert,
});

const mapDispatchToProps = {
  hideAlertMessage,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(Layout);
```

**Comment by 2060digital** [comment]
This seems to work, but for some reason creates duplicate alerts for me (every time the action is dispatched, two alert messages are created).

**Comment by glevha** [comment]
Very sorry for my late answer @falloutghost. Your solution is great, thanks a lot !

**Comment by diegoalmesp** [comment]
Hello guys! I'm also trying to make it work with redux, but I don't understand the "AlertContainer" part.
That doesn't look like a react component, how can I import it? or is it a custom component? If that's so, could you please provide an example?

thanks in advance!

(btw, the library looks great, exactly what I was looking for)

**Comment by kauffmanes** [comment]
@diegoalmesp did you ever find out where it's coming from?

**Comment by benbieler** [comment]
For the use with redux: https://github.com/diegoddox/react-redux-toastr#readme 

its much better
