### ISSUE TITLE
Can i change the look and feel of the component apart from the available themes? can i have this component wrapped in a component like card?

### ISSUE THREAD

**Issue by DevPuvi99** [schiehll/react-alert#48]
i want to have green color border and background fill  for success; red color for error, yellow color for warning and blue color for info. Is it possible to customize this component like that? please, let me know if there are any workaround possible.

Also please let me know if i can position this component inside a  card apart from the positioning options available? I placed the alert component inside card. but the alert is always getting displayed outside the card.
Thanks.

**Comment by schiehll** [comment]
With v3 you can now create custom alert templates! But still isn't possible to show an alert relative to a component, it will be always relative to the page.
