### ISSUE TITLE
React v16.x support

### ISSUE THREAD

**Issue by shogochiai** [schiehll/react-alert#49]
`react-alert@2.4.0 requires a peer of react@^15.5.4 but none was installed`

**Comment by shogochiai** [comment]
For enabling that `enzyme@2.9.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x but none was installed.` required

**Comment by Jeyloh** [comment]
What is the status here? Will React v.16x be supported anytime soon?

**Comment by schiehll** [comment]
v3 works with react 16! Sorry about the delay.

**Comment by shogochiai** [comment]
Thanks for your contribution 3>
