### ISSUE TITLE
how to use this component when server render

### ISSUE THREAD

**Issue by TommyLike** [schiehll/react-alert#6]
I want to use this component in my project,but as I use server render so when include this packages the project failed as below:

```
 ReferenceError: document is not defined 
 ReferenceError: window is not defined 
```

how can i fix it?

**Comment by schiehll** [comment]
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.
