### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2_react_dom___default.a.createPortal is not a function at WithAlert.render (react-alert.js:550)

### ISSUE THREAD

**Issue by RyanThomas95** [schiehll/react-alert#65]
Any help?

**Comment by schiehll** [comment]
Looks like your version of `react-dom` doesn't have the `createPortal` function. It was introduced in version 16.2.0, so please make sure you project meet the peer dependencies requirements.

**Comment by RyanThomas95** [comment]
Thanks! Sorry, I thought I had it updated
