### ISSUE TITLE
Everything inside Provider disappears

### ISSUE THREAD

**Issue by kartik0709** [schiehll/react-alert#66]
If I'm at the homepage and if I press the link to the homepage twice, everything inside the provider disappears.

**Comment by schiehll** [comment]
@kartik0709, sorry, but you will have to explain better what's happening. Show us some minimal way of reproduce it. You can fork this [codesandbox](https://codesandbox.io/s/l2mo430lzq) and try to reproduce the problem, then paste the link here so we can help you.

**Comment by kartik0709** [comment]
Sure. Here you go - https://codesandbox.io/s/8k35mww060
When we click on Home, the entire body inside AlertProvider disappears.

**Comment by schiehll** [comment]
Thank you!

So here's the problem: you have to put the `AlertProvider` in your root component, in this case the `index.js` file.

Here: https://codesandbox.io/s/p58lwy3kvx

Hope it helps.

**Comment by kartik0709** [comment]
Oh, thanks a lot! Can you mention this in the guide too? so no-one else makes the same mistake.
