### ISSUE TITLE
Not compatible with Next.js - render blank page on client side

### ISSUE THREAD

**Issue by flexlee** [schiehll/react-alert#68]
Trying to use react-alert with Nextjs. I copied the example to wrap my page with `<AlertProvider />`. However, if I hit `/` link on the client side when I'm already on `/`, it will render a blank page. The same is true if I go to any route I'm already on.

Please clone an example repo `https://github.com/flexlee/nextjs-react-alert`. And run `yarn`, `yarn start`. In the browser, if you click the "home" link, you will see a blank page.

**Comment by flexlee** [comment]
Nextjs doesn't have a root component. So can't use v3 `<AlertProvider />`. Have to switch back to react-alert v2.

**Comment by schiehll** [comment]
Yeah sorry, looks like we would have to do something specific to to do it work, like they do with other libs in the examples.

I do not really use Next but if anyone want to try to make it work I would accept a PR to include the link of the package in the README or even better, if anyone manage to make it work without a specific adapter I would accept PR with the code too.

**Comment by schiehll** [comment]
Actually I've just tested the new version `3.2.0` cloning you repository and it seems to work!

Can you please confirm that updating to the latest release solves the issue?

**Comment by schiehll** [comment]
I will close it since it's working for me. If you find the same problem again, please reopen.
