### ISSUE TITLE
Did you have example for confirm dialog using this package?

### ISSUE THREAD

**Issue by aligos** [schiehll/react-alert#7]
i want to make confirm dialog ok and cancle with this alert

**Comment by dherran** [comment]
As per my experience with the module it seems to only support alerts.

**Comment by schiehll** [comment]
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.

**Comment by karensg** [comment]
Would be awesome though to support confirm as well as it is the best library for react around
