### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by bgold0** [schiehll/react-alert#85]
really which this could be ported to react native.

**Comment by schiehll** [comment]
Hey @bgold0,

Sorry, it's not possible right now since we are using DOM things like `div`s and also portals.

If someone that uses `react-native` want to try to make it compatible while making sure that it still works in the DOM and without adding too much weight, I would accept the PR.

**Comment by sturmenta** [comment]
It could be possible to use react-alert in react-native but [without using react-transition-group](https://github.com/reactjs/react-transition-group/issues/6#issuecomment-407628996)
