### ISSUE TITLE
React.createContext is not a function!

### ISSUE THREAD

**Issue by mr-bat** [schiehll/react-alert#86]
I just installed the module but looks like it's incompatible with the latest version of react.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/16259723/41287826-4582f64e-6e59-11e8-8939-d256380a3a85.png">

**Comment by schiehll** [comment]
Hey @mr-bat,

I'm pretty sure it's compatible with the latest version of react, you can check it [here](https://codesandbox.io/s/l2mo430lzq) (check the dependencies). Also, the `createContext` api was introduced in v16.3 so updating react to v16.4 would not break it this way.

Maybe you are not using the latest version of react, are you sure you are? This error is supposed to happen if you are using react with a version < 16.3.0.

Hope it helps.
