### ISSUE TITLE
Uncaught Error: Element type is invalid

### ISSUE THREAD

**Issue by dldugan14** [schiehll/react-alert#89]
While using this with redux and react router 4 and fallowing the usage directions it immediately throws this error:

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (invariant.js:42)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:72)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:364)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)

I cannot for the life of me figure out why. I have tried the suggested versions of all the dependencies as well as their respective @latest 

The code looks something like this:

import { Provider as AlertProvider } from "react-alert";
import AlertTemplate from "react-alert-template-basic";

const options = {
  position: "bottom center",
  timeout: 5000,
  offset: "30px",
  transition: "scale"
};

<Provider store={store}>
      <AlertProvider template={AlertTemplate} {...options}>
        <ConnectedRouter history={history}>
          <App>
            <div id="app-header">
              <Route path="/" component={Header} />
            </div>

            <div id="app-content">
              <div id="app-content-container">
                <Route exact path="/" component={foobar} />
                //more routes here 
              </div>
            </div>

            <div id="app-navigation">
              <Route path="/" component={Footer} />
            </div>
          </App>
        </ConnectedRouter>
      </AlertProvider>
    </Provider>

**Comment by dldugan14** [comment]
sorry something went wrong with the code block here is

`import { Provider as AlertProvider } from "react-alert";
import AlertTemplate from "react-alert-template-basic";

const options = {
  position: "bottom center",
  timeout: 5000,
  offset: "30px",
  transition: "scale"
};

type RootType = {
  store: {},
  history: {}
};

export default function Root({ store, history }) {
  return (
    <Provider store={store}>
      <AlertProvider template={AlertTemplate} {...options}>
        <ConnectedRouter history={history}>
          <App>
            <div id="app-header">
              <Route path="/" component={Header} />
            </div>

            <div id="app-content">
              <div id="app-content-container">
                <Route exact path="/" component={foobar} />
            //more routes
              </div>
            </div>

            <div id="app-navigation">
              <Route path="/" component={Footer} />
            </div>
          </App>
        </ConnectedRouter>
      </AlertProvider>
    </Provider>`

**Comment by travis** [comment]
Any ideas on this? I'm seeing the same thing trying to render a component using `react-alert` in storyshots. Can provide code sample if that'd be helpful!

**Comment by lewjc** [comment]
@travis Did you ever resolve this? having the same issue.

**Comment by daviskoh** [comment]
Not sure if this is helpful, but also using `react-router-dom`. Had this error when I accidentally imported `Provider` instead of `{ Provider }`.

After fixing I ran into an error `Unexpected Fiber popped` & `cannot set property '_currentValue' of undefined` which were resolved by making sure both `react` & `react-dom` versions were `>=16.3.1`

**Comment by shorif2000** [comment]
i am getting this as well. i am using redux and router

**Comment by jacobsowles** [comment]
Ah, here's the fix for your code, @travis:

In App.js, change this:

```
export default withRouter(
  connect(
    mapStateToProps,
    mapDispatchToProps
  )
)(App);
```

to this:

```
export default withRouter(
  connect(
    mapStateToProps,
    mapDispatchToProps
  )(App)
); // note that withRouter wraps the whole thing
```
...and update your mapStateToProps from this:

```
function mapStateToProps(state) {
  return state;
}
```
to this:
```
function mapStateToProps(state) {
  return { ...state };
}
```
