### ISSUE TITLE
Add a customClass Props to the main div of the component

### ISSUE THREAD

**Issue by bastoune** [schiehll/react-alert#93]
For now, the component happens a div into the body.
It is impossible to access this div and customize some CSS (like & z-index).

Is it possible to add an option that will add a `className` to that div ?

**Comment by emmya** [comment]
+1

**Comment by emmya** [comment]
Easy fix would be to add a className to the wrapper so styles are customizable.

**Comment by redheal** [comment]
+1

**Comment by bandaiah8** [comment]
+1

**Comment by jkhaui** [comment]
+1

**Comment by schiehll** [comment]
In v5 is now possible to pass a `containerStyle` option to the Provider with styles you want to be applied to the alerts container.
